Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 71, in auth_register
    raise InputError(description='Invalid email')
error.InputError: 400 Bad Request: Invalid email
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 75, in auth_register
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 75, in auth_register
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 73, in auth_register
    raise InputError(description='Email already in use')
error.InputError: 400 Bad Request: Email already in use
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 89, in svr_auth_register
    email = req['email']
KeyError: 'email'
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 89, in svr_auth_register
    email = req['email']
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 23, in auth_login
    raise InputError(description='Email not registered')
error.InputError: 400 Bad Request: Email not registered
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 25, in auth_login
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 21, in auth_login
    raise InputError(description='Invalid email')
error.InputError: 400 Bad Request: Invalid email
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 21, in auth_login
    raise InputError(description='Invalid email')
error.InputError: 400 Bad Request: Invalid email
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 25, in auth_login
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 81, in svr_auth_login
    email = req['email']
KeyError: 'email'
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 81, in svr_auth_login
    email = req['email']
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 71, in auth_register
    raise InputError(description='Invalid email')
error.InputError: 400 Bad Request: Invalid email
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 75, in auth_register
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 75, in auth_register
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 73, in auth_register
    raise InputError(description='Email already in use')
error.InputError: 400 Bad Request: Email already in use
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 89, in svr_auth_register
    email = req['email']
KeyError: 'email'
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 89, in svr_auth_register
    email = req['email']
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 23, in auth_login
    raise InputError(description='Email not registered')
error.InputError: 400 Bad Request: Email not registered
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 25, in auth_login
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 21, in auth_login
    raise InputError(description='Invalid email')
error.InputError: 400 Bad Request: Invalid email
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 21, in auth_login
    raise InputError(description='Invalid email')
error.InputError: 400 Bad Request: Invalid email
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 25, in auth_login
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 81, in svr_auth_login
    email = req['email']
KeyError: 'email'
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 81, in svr_auth_login
    email = req['email']
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 71, in auth_register
    raise InputError(description='Invalid email')
error.InputError: 400 Bad Request: Invalid email
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 75, in auth_register
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 75, in auth_register
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 73, in auth_register
    raise InputError(description='Email already in use')
error.InputError: 400 Bad Request: Email already in use
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 89, in svr_auth_register
    email = req['email']
KeyError: 'email'
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 89, in svr_auth_register
    email = req['email']
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 23, in auth_login
    raise InputError(description='Email not registered')
error.InputError: 400 Bad Request: Email not registered
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 25, in auth_login
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 21, in auth_login
    raise InputError(description='Invalid email')
error.InputError: 400 Bad Request: Invalid email
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 21, in auth_login
    raise InputError(description='Invalid email')
error.InputError: 400 Bad Request: Invalid email
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 25, in auth_login
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 81, in svr_auth_login
    email = req['email']
KeyError: 'email'
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 81, in svr_auth_login
    email = req['email']
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 99, in svr_auth_logout
    token = req['token']
KeyError: 'token'
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 99, in svr_auth_logout
    token = req['token']
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/home/gabriel/C/UNSW/project/src/channel.py", line 24, in channel_invite
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/home/gabriel/C/UNSW/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 124, in svr_channel_invite
    return channel.channel_invite(token, channel_id, user_id)
  File "/home/gabriel/C/UNSW/project/src/channel.py", line 26, in channel_invite
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/home/gabriel/C/UNSW/project/src/channel.py", line 30, in channel_invite
    data.resolve_user_id_index(user_id)
  File "/home/gabriel/C/UNSW/project/src/data.py", line 73, in resolve_user_id_index
    raise LookupError("user id not found")
LookupError: user id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 124, in svr_channel_invite
    return channel.channel_invite(token, channel_id, user_id)
  File "/home/gabriel/C/UNSW/project/src/channel.py", line 32, in channel_invite
    raise InputError(description='Invalid User ID')
error.InputError: 400 Bad Request: Invalid User ID
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 121, in svr_channel_invite
    token = req['token']
KeyError: 'token'
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 121, in svr_channel_invite
    token = req['token']
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/home/gabriel/C/UNSW/project/src/channel.py", line 66, in channel_details
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/home/gabriel/C/UNSW/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 133, in svr_channel_details
    result = channel.channel_details(token, channel_id)
  File "/home/gabriel/C/UNSW/project/src/channel.py", line 68, in channel_details
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 130, in svr_channel_details
    token = req['token']
  File "/home/gabriel/.local/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 71, in auth_register
    raise InputError(description='Invalid email')
error.InputError: 400 Bad Request: Invalid email
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 75, in auth_register
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 75, in auth_register
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 77, in auth_register
    raise InputError(description='Invalid first name or last name')
error.InputError: 400 Bad Request: Invalid first name or last name
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 93, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 73, in auth_register
    raise InputError(description='Email already in use')
error.InputError: 400 Bad Request: Email already in use
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 89, in svr_auth_register
    email = req['email']
KeyError: 'email'
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 89, in svr_auth_register
    email = req['email']
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 23, in auth_login
    raise InputError(description='Email not registered')
error.InputError: 400 Bad Request: Email not registered
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 25, in auth_login
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 21, in auth_login
    raise InputError(description='Invalid email')
error.InputError: 400 Bad Request: Invalid email
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 21, in auth_login
    raise InputError(description='Invalid email')
error.InputError: 400 Bad Request: Invalid email
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 83, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/home/gabriel/C/UNSW/project/src/auth.py", line 25, in auth_login
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 81, in svr_auth_login
    email = req['email']
KeyError: 'email'
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 81, in svr_auth_login
    email = req['email']
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 99, in svr_auth_logout
    token = req['token']
KeyError: 'token'
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 99, in svr_auth_logout
    token = req['token']
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/home/gabriel/C/UNSW/project/src/channel.py", line 24, in channel_invite
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/home/gabriel/C/UNSW/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 124, in svr_channel_invite
    return channel.channel_invite(token, channel_id, user_id)
  File "/home/gabriel/C/UNSW/project/src/channel.py", line 26, in channel_invite
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/home/gabriel/C/UNSW/project/src/channel.py", line 30, in channel_invite
    data.resolve_user_id_index(user_id)
  File "/home/gabriel/C/UNSW/project/src/data.py", line 73, in resolve_user_id_index
    raise LookupError("user id not found")
LookupError: user id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 124, in svr_channel_invite
    return channel.channel_invite(token, channel_id, user_id)
  File "/home/gabriel/C/UNSW/project/src/channel.py", line 32, in channel_invite
    raise InputError(description='Invalid User ID')
error.InputError: 400 Bad Request: Invalid User ID
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 121, in svr_channel_invite
    token = req['token']
KeyError: 'token'
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 121, in svr_channel_invite
    token = req['token']
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/home/gabriel/C/UNSW/project/src/channel.py", line 66, in channel_details
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/home/gabriel/C/UNSW/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 133, in svr_channel_details
    result = channel.channel_details(token, channel_id)
  File "/home/gabriel/C/UNSW/project/src/channel.py", line 68, in channel_details
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "src/server.py", line 41, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 130, in svr_channel_details
    token = req['token']
  File "/home/gabriel/.local/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
