Traceback (most recent call last):
  File "src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 84, in svr_auth_register
    email = req['email']
KeyError: 'email'
Traceback (most recent call last):
  File "src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 84, in svr_auth_register
    email = req['email']
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 76, in svr_auth_login
    email = req['email']
KeyError: 'email'
Traceback (most recent call last):
  File "src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 76, in svr_auth_login
    email = req['email']
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 84, in svr_auth_register
    email = req['email']
KeyError: 'email'
Traceback (most recent call last):
  File "src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 84, in svr_auth_register
    email = req['email']
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 76, in svr_auth_login
    email = req['email']
KeyError: 'email'
Traceback (most recent call last):
  File "src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "src/server.py", line 76, in svr_auth_login
    email = req['email']
TypeError: list indices must be integers or slices, not str
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 90, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/auth.py", line 73, in auth_register
    raise InputError(description='Email already in use')
error.InputError: 400 Bad Request: Email already in use
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 90, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/auth.py", line 73, in auth_register
    raise InputError(description='Email already in use')
error.InputError: 400 Bad Request: Email already in use
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 90, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/auth.py", line 73, in auth_register
    raise InputError(description='Email already in use')
error.InputError: 400 Bad Request: Email already in use
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 129, in svr_channel_details
    return channel.channel_details(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/channel.py", line 100, in channel_details
    'profile_img_url': user_list[index]['profile_img_url']
KeyError: 'profile_img_url'
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 129, in svr_channel_details
    return channel.channel_details(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/channel.py", line 100, in channel_details
    'profile_img_url': user_list[index]['profile_img_url']
KeyError: 'profile_img_url'
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/channel.py", line 66, in channel_details
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 129, in svr_channel_details
    return channel.channel_details(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/channel.py", line 68, in channel_details
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 90, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/auth.py", line 75, in auth_register
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 368, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 140, in svr_channel_messages
    for i, usr in enumerate(result['all_members']):
KeyError: 'all_members'
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 376, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/channel.py", line 66, in channel_details
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 129, in svr_channel_details
    return channel.channel_details(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/channel.py", line 68, in channel_details
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 376, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 141, in svr_channel_messages
    for i, usr in enumerate(result[t + '_members']):
KeyError: 'all_members'
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 141, in svr_channel_messages
    for i, usr in enumerate(result[t + '_members']):
KeyError: 'all_members'
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 376, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 90, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/auth.py", line 75, in auth_register
    raise InputError(description='Invalid password')
error.InputError: 400 Bad Request: Invalid password
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 142, in svr_channel_messages
    for i, usr in enumerate(result[t + '_members']):
KeyError: 'all_members'
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 377, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 378, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 143, in svr_channel_messages
    for i, usr in enumerate(result[t + '_members']):
KeyError: 'owner_members'
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 378, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 143, in svr_channel_messages
    for i, usr in enumerate(result[t + '_members']):
KeyError: 'owner_members'
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 143, in svr_channel_messages
    for i, usr in enumerate(result[t + '_members']):
KeyError: 'owner_members'
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 379, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 379, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 143, in svr_channel_messages
    for i, usr in enumerate(result[t + '_members']):
KeyError: 'owner_members'
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 376, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 376, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/channel.py", line 66, in channel_details
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 130, in svr_channel_details
    result = channel.channel_details(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/channel.py", line 68, in channel_details
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 376, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 376, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 376, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 376, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 376, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 376, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 375, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 376, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/channel.py", line 66, in channel_details
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 130, in svr_channel_details
    result = channel.channel_details(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/channel.py", line 68, in channel_details
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 381, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 80, in svr_auth_login
    return auth.auth_login(email, pwd)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/auth.py", line 23, in auth_login
    raise InputError(description='Email not registered')
error.InputError: 400 Bad Request: Email not registered
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 375, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 375, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 375, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 375, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 375, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 375, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 375, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 375, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 375, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 319, in svr_user_profile_uploadphoto
    return user.user_profile_uploadphoto(token, url, x_start, y_start, x_end, y_end)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/user.py", line 149, in user_profile_uploadphoto
    raise InputError(description="Incorrect crop parameters")
error.InputError: 400 Bad Request: Incorrect crop parameters
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 319, in svr_user_profile_uploadphoto
    return user.user_profile_uploadphoto(token, url, x_start, y_start, x_end, y_end)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/user.py", line 149, in user_profile_uploadphoto
    raise InputError(description="Incorrect crop parameters")
error.InputError: 400 Bad Request: Incorrect crop parameters
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 375, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 281, in svr_user_profile
    if result['user'][i]['profile_img_url'] != "":
NameError: name 'i' is not defined
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 381, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 90, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/auth.py", line 73, in auth_register
    raise InputError(description='Email already in use')
error.InputError: 400 Bad Request: Email already in use
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 90, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/auth.py", line 73, in auth_register
    raise InputError(description='Email already in use')
error.InputError: 400 Bad Request: Email already in use
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 322, in svr_user_profile_uploadphoto
    return user.user_profile_uploadphoto(token, url, x_start, y_start, x_end, y_end)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/user.py", line 149, in user_profile_uploadphoto
    raise InputError(description="Incorrect crop parameters")
error.InputError: 400 Bad Request: Incorrect crop parameters
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 322, in svr_user_profile_uploadphoto
    return user.user_profile_uploadphoto(token, url, x_start, y_start, x_end, y_end)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/user.py", line 149, in user_profile_uploadphoto
    raise InputError(description="Incorrect crop parameters")
error.InputError: 400 Bad Request: Incorrect crop parameters
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 322, in svr_user_profile_uploadphoto
    return user.user_profile_uploadphoto(token, url, x_start, y_start, x_end, y_end)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/user.py", line 149, in user_profile_uploadphoto
    raise InputError(description="Incorrect crop parameters")
error.InputError: 400 Bad Request: Incorrect crop parameters
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 90, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/auth.py", line 71, in auth_register
    raise InputError(description='Invalid email')
error.InputError: 400 Bad Request: Invalid email
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 90, in svr_auth_register
    return auth.auth_register(email, pwd, fname, lname)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/auth.py", line 71, in auth_register
    raise InputError(description='Invalid email')
error.InputError: 400 Bad Request: Invalid email
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 322, in svr_user_profile_uploadphoto
    return user.user_profile_uploadphoto(token, url, x_start, y_start, x_end, y_end)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/user.py", line 149, in user_profile_uploadphoto
    raise InputError(description="Incorrect crop parameters")
error.InputError: 400 Bad Request: Incorrect crop parameters
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 381, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 381, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 381, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 76, in standup_active
    channel_index = data.resolve_channel_id_index(channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/data.py", line 89, in resolve_channel_id_index
    raise LookupError("channel id not found")
LookupError: channel id not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 38, in wrapper
    return json.dumps(func(*args, **kwargs))
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/server.py", line 381, in svr_standup_active
    return standup.standup_active(token, channel_id)
  File "/Users/Yash/Google Drive/School/uni/COMP1531/Project/project/src/standup.py", line 78, in standup_active
    raise InputError(description='Invalid Channel ID')
error.InputError: 400 Bad Request: Invalid Channel ID
